### ISSUE TITLE
The mod Extra Ship Components NEXT Overwrites: Component Progression seems not work

### ISSUE THREAD

**Issue by Diadormu** [Solovyev-Pavel/nh_esc_next#13]
this is a picture for Citadel, weapons components and shield are not auto upgraded
only import ui mod、_esc_ and _ESC: Component Progression_. 
i used "research_all_technologies 1 0" command to unlocked all techs
![20230804224826_1](https://github.com/Solovyev-Pavel/nh_esc_next/assets/40790147/4b228edb-1e92-49e8-af82-874387a8fec4)

**Comment by Solovyev-Pavel** [comment]
starbases (and to lesser extent civilian ships) have always been wonky, even in base game. Unfortunately, I do not know any reliable way enforce proper upgrades on those. The fact that you got *some* components there to upgrade properly is remarkable.

**Comment by Diadormu** [comment]
> starbases (and to lesser extent civilian ships) have always been wonky, even in base game. Unfortunately, I do not know any reliable way enforce proper upgrades on those. The fact that you got _some_ components there to upgrade properly is remarkable.

I started a normal game for test and the mod worked, so I guess it's only useless when using the command line unlock techs 😢 .
