### ISSUE TITLE
Request: Rename economic plan file to enable overrides via load order

### ISSUE THREAD

**Issue by TheDogKSP** [Solovyev-Pavel/nh_esc_next#2]
You are overwriting the basic economic plan, and in such a way (with a custom file), that I cannot re-override it with a simple load order change... :(

Request: could you rename esc_economic_plans.txt into "01_base.txt", so that I can make use of the load order to have other mod provide other plans?

**Comment by Solovyev-Pavel** [comment]
will be replaced with partial plan that compliments vanilla one (rather than replacing it) with 3.3 update
