### ISSUE TITLE
No distinguishable difference between nanite torpedoes

### ISSUE THREAD

**Issue by Alexis-Grimm** [Solovyev-Pavel/nh_esc_next#5]
The Nanite Warhead Torpedo and Gray Goo Torpedo appear to have the exact same stats, except gray goo costs more, looking through the script I can't find anything that would indicate there is a hidden improvement that the game doesn't show.

**Comment by Solovyev-Pavel** [comment]
Yeah, that was an error. Gray Goo Torpedo should have higher damage.

Fixed.
